### ISSUE TITLE
Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) 

### ISSUE THREAD

**Issue by SaryElgmal** [mareimorsy/DB#5]
Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /home/u489986511/public_html/DB.php on line 800

I'm not php developer this could be a simple issue but please refer back if I'm wrong.

**Comment by shqawe1** [comment]
simply go to DB.php file and search about this line 
`public function list($field)`
and change the name of function from list to lists like this 
`public function lists($field)`
and it will work 
واي خدمة حاضرين اخوي ساري

**Comment by SaryElgmal** [comment]
الف شكري اخوي
